version: "3.7"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: root@123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - ./.docker/mssql:/data/mssql
    networks:
      - sql-server-network

networks:
  sql-server-network:
